### PR TITLE
Rebased #96: Create repos for non-organizations

### PR DESCRIPTION
**Pull request by abitrolly**
This needs a thorough review. I just rebased the changes to make them mergeable and solved conflicts without digging too much into how GitHub provider currently handles all parameters. Especially `func (c *Config) Client()` seem wrong to me.

### CODE REVIEW

**Comment by anGie44** [comment]
thank you @abitrolly for this rebase! if you plan on contributing more to this work please note i've similarly taken the original PR and merged w/the current state of master to create this WIP PR https://github.com/terraform-providers/terraform-provider-github/pull/428.

**Comment by abitrolly** [comment]
@anGie44 tests in #428 still do not pass.

**Comment by anGie44** [comment]
ah yes @abitrolly, good catch! I think an addition to these 2 [files](https://github.com/terraformtesting/acceptance-tests/commit/3eabdb92367d8981d593d3a5959937c5ce52f8ce) should help in the tests that look for the new `GITHUB_BASE_URL`

**Comment by abitrolly** [comment]
#428 is deprecated and now the progress is being done in https://github.com/terraform-providers/terraform-provider-github/milestone/8

**Comment by abitrolly** [comment]
Superseded by #464 and #465.

**Pull request closed without merging**
