### PR TITLE
Update go-github to v25

### PR DESCRIPTION
**Pull request by bramwelt**
This updates the go-github module used by the Terraform Github provider to v25.
v22-23 are skipped due to a bug introduced and later fixed related to webhooks.

### CODE REVIEW

**Comment by bramwelt** [comment]
This builds off the work done in #186.

**Comment by bramwelt** [comment]
@radeksimko @mattburgess @joestump @appilon Could I get a review please?

**Comment by bltavares** [comment]
@bramwelt There has been a recent release `v25`of `go-github`. Would it be interesting to take the chance to bump it before, so we can make a single release?

**Comment by bramwelt** [comment]
@bltavares Done!

**Comment by bramwelt** [comment]
@bflad I'm sure you're super busy, but if you have a quick moment next week or this to quickly look over this PR and point out if there are any glaring issues/approach that needs to be addressed, it'd be super appreciated!

**Comment by paultyng** [comment]
`2.0.0` has been released with go-github v25.0.2

**Pull request closed without merging**
