### PR TITLE
Added `allowsDeletions`and `allowsForcePushes`settings

### PR DESCRIPTION
**Pull request by frbayart**
In the latest Github GraphQL schema  https://developer.github.com/v4/changelog/2020-11-13-schema-changes/ we can manage the rules applied to everyone including administrators.

I have updated https://github.com/shurcooL/githubv4 to add `allowsDeletions`and `allowsForcePushes`settings.

And now I would like to suggest adding it to the related Terraform provider.

### CODE REVIEW

**Comment by frbayart** [comment]
@jcudit What can I do about "failing checks"?

**Comment by jcudit** [comment]
@frbayart please ignore the failed acceptance tests.  There are issues with running them from forks.

The TravisCI [failure](https://travis-ci.org/github/terraform-providers/terraform-provider-github/jobs/748003885) is relevant though:

> ERRO Running error: inspect: analysis skipped: errors in package: [/home/travis/gopath/src/github.com/terraform-providers/terraform-provider-github/main.go:5:2: could not import github.com/terraform-providers/terraform-provider-github/github (/home/travis/gopath/src/github.com/terraform-providers/terraform-provider-github/github/resource_github_branch_protection.go:250:3: unknown field AllowsDeletions in struct literal)] 

I _think_ its complaining because the latest changes to ` shurcooL/githubv4` are not vendored in.  Please run `go mod vendor` and check in the `vendor/` directory.

Feel free to cherry-pick [this commit](https://github.com/terraform-providers/terraform-provider-github/commit/edd6395f7ce305ae24a1e12b5818f275bb5b6701) as well to get a test included.

**Comment by frbayart** [comment]
`go mod vendor` is correct now, I can see `AllowsDeletions`.

I have included the test (now I know what I should do for the next time).

I have aligned my branch with `master` I hope it was not an error, else I will recreate a new PR let me know.

**Review by jcudit — APPROVED** [review]

**Comment by neilmookerjea** [comment]
Did it get added to the Github provider yet? I have:
`Terraform v0.14.4
+ provider registry.terraform.io/integrations/github v4.3.0
Your version of Terraform is out of date! The latest version
is 0.14.5. You can update by downloading from https://www.terraform.io/downloads.html`
Getting:
`Error: Field 'allowsDeletions' doesn't exist on type 'BranchProtectionRule'`

**Comment by frbayart** [comment]
I use it on 
```
      source  = "integrations/github"
      version = "4.2.0"
```

and my usage is:

```
resource "github_branch_protection" "branch" {
  provider = kensu-github

  for_each = var.branches

  pattern                = each.value["pattern"]
  repository_id          = github_repository.repository.node_id
  enforce_admins         = true
  allows_deletions       = each.value["allows_deletions"]
  allows_force_pushes    = false
  require_signed_commits = true
```

**Comment by neilmookerjea** [comment]
I see you used `provider` argument inside the resource and it's set to `kensu-github`
Does that mean `integrations/github` is overwritten there?
Also I don't see `provider` as one of the arguments accepted [here](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/branch_protection#argument-reference)
Can you post the output of `terraform providers` command?

However it's interesting to see this option. I have repos from different org. I could not figure out a way to have different variables (env) for the field `organization` under `github` provider. It accepts `GITHUB_ORGANIZATION` env variable. But that's set to a single value when I run the plan.

**Pull request merged**
