### PR TITLE
Teams may be nested

### LINKED ISSUE #47: Support to create Teams and Child Teams?
### Terraform Version
v10.2

### Affected Resource(s)
- github_team

https://github.com/blog/2378-nested-teams-add-depth-to-your-team-structure

### PR DESCRIPTION
**Pull request by alindeman**
Allows a `github_team` to have a `parent_team_id`.

Resolves #47

### CODE REVIEW

**Comment by alindeman** [comment]
@radeksimko Nested team support has landed in `go-github` master, so this is ready for review.

**Comment by willejs** [comment]
@alindeman I was just about to make this PR, nice work! Could you resolve conflicts then perhaps we could poke radeksimko on here or hangops...

**Comment by alindeman** [comment]
> @alindeman I was just about to make this PR, nice work! Could you resolve conflicts then perhaps we could poke radeksimko on here or hangops...

Yup, I'll rebase this shortly.

**Comment by alindeman** [comment]
@willejs @radeksimko Alright, I've rebased on top of the latest master: this is ready for review again.

**Comment by kremlinkev** [comment]
Any movement on this?

**Comment by BastienM** [comment]
Hi,
Any eta for a merge ?

**Comment by basejumpa** [comment]
👍 I could really need this in a release. Is there any chance to have some v1.1.0 available before end of May 2018?

**Comment by majormoses** [comment]
I need this as well, right now it requires creating the teams and then going to the UI to update which is ugly.

**Comment by paultyng** [comment]
Closed in a60a056c07d8bd15dfcb6d525ffd18a2ffbbd07f

**Comment by paultyng** [comment]
This was released in v1.1.0

**Pull request closed without merging**
