### PR TITLE
Gh 327 configure repo as template

### PR DESCRIPTION
**Pull request by benj-fletch**

### CODE REVIEW

**Comment by yordis** [comment]
@jcudit do you think would be worth trying to merge this one? Seems really small

**Comment by jcudit** [comment]
@yordis - yes!

I think this makes sense for the next feature release.  I have it tracked and plan to 🚢 in the next batch.

**Comment by jcudit** [comment]
@benj-fletch - I'd like to get this one merged into the `v2.6.0` release.  Do you have time to fix the conflicts here?  I can push to merge shortly after they've been resolved.

**Comment by benj-fletch** [comment]
Hey @jcudit thanks for another look at this. Hopefully my last push should resolve all of the conflicts with master

**Pull request merged**
