### PR TITLE
Add Apps to actor types in branch protection

### PR DESCRIPTION
**Pull request by patrickmarabeas**
Adding Github Apps to actor types in the branch protection resource.

NOTE: Apps as an actor type is only available in push restrictions.

Resolves: #581

Resolves a comment in #572

### CODE REVIEW

**Review by jcudit — APPROVED** [review]

**Comment by lorengordon** [comment]
oh wow, this has been driving me crazy for the last hour. couldn't figure out why the branch protection resource kept telling me it couldn't resolve the ID of the mergify app. decided to configure it manually, import the resource, and run the plan to see what was up, and even then the mergify app was just skipped in the plan output and not present in the tfstate. so started investigating open issues, just to find a likely patch was merged 6 hours ago! serendipity! looking forward to the release!

**Comment by lorengordon** [comment]
Hmm, well, so far, this still isn't working for me... trying to add the `mergify[bot]` app/user:

```
Error: Could not resolve to User, Team, or App node with the global id of 'MDM6Qm90Mzc5MjkxNjI='
```

Pretty sure I have the correct node_id: https://api.github.com/users/mergify[bot]? Am I just using this wrong?

**Comment by lorengordon** [comment]
Ok, it is working. I was able to manually setup the branch protection, then remove it from tfstate and import it to find the correct node_id: `MDM6QXBwMTA1NjI=`. Now how to figure out what username that is...

**Comment by lorengordon** [comment]
Alright, GitHub Apps are just weird. Knowing it's an app, this gets the correct node_id: https://api.github.com/apps/mergify.

But there is no terraform data source for github apps, and even if there were, to lookup users/teams/apps from the friendly-name, I'd have to split the node_ids by type to map them to data sources, then combine the results for the `push_restrictions` list. Blech.

**Pull request merged**
